### ISSUE TITLE
Script update doesnt fix the Vr not working

### ISSUE THREAD

**Issue by chesse20** [TheNexusAvenger/Nexus-VR-Character-Model-Legacy#4]
Updated the studio copies of the roblox vr scripts and it still did not work with my vive. also don't close github issues unless you are 100% they are actually fixed 😋

**Comment by TheNexusAvenger** [comment]
I can't reproduce this with the patch I applied. I have tested with 2 headsets, including the Vive, on a VR ready laptop. From my point of view, it was resolved. Your best move may be to post a bug report with VREnabled reading false.

**Comment by TheNexusAvenger** [comment]
The repro steps ended up being to use an account that wasn't mine. The F9 console gave me a warning for an infinite yield on a WaitForChild caused by this line:
`local Character = MainCharacterCreator:CreateLocalCharacter(game.Workspace:WaitForChild("TheNexusAvenger"))`
This was used in development, but was never removed. It should be working now. If it isn't please provide a picture of the F9 console.
I will automatically close it tomorrow (Thursday) night if I don't see a response.

**Comment by chesse20** [comment]
still having issues, struglling to read the developer console becuase it doesn't work very well in vr

**Comment by TheNexusAvenger** [comment]
Can you take a screenshot?

**Comment by chesse20** [comment]
https://www.roblox.com/games/1192536269/Parkour-Simulator-Release#
i just put the current free model of the script as is into this game, and it works except the player head is stuck in the floor. I can't figure out how to check the dev console still though. 

Also trying to rejoin a server after you are playing in vr and then come back doesn't work

**Comment by TheNexusAvenger** [comment]
Rejoining I will need to investigate. Since you are a developer forum member, I would suggest making a bug report on that, or adding a feature to make an event for headsets getting recentered to allow custom Y axis offsets.

**Comment by TheNexusAvenger** [comment]
Actually, the recenter functionality is something I may use rather than relying on the floor. I have a feeling it is a driver bug with the Microsoft Mixed Reality not setting the base to the head on start. Once that is up, I will close this.

**Comment by TheNexusAvenger** [comment]
I have released an update regarding the head being stuck in the ground. The character will no be recentered on spawn. Please create a new issue if there is a problem with that.
